-- Роль: SHOP_WRITER_ROLE

GRANT SHOP_WRITER_ROLE TO CREATOR;

-- Привилегии роли:
GRANT CREATE SESSION TO SHOP_WRITER_ROLE;
GRANT CREATE TABLE TO SHOP_WRITER_ROLE;
GRANT DELETE ON SHOP.ZAKAZ TO SHOP_WRITER_ROLE;
GRANT INSERT ON SHOP.ZAKAZ TO SHOP_WRITER_ROLE;
GRANT SELECT ON SHOP.ZAKAZ TO SHOP_WRITER_ROLE;
GRANT UPDATE ON SHOP.ZAKAZ TO SHOP_WRITER_ROLE;
