-- Роль: SHOPROLERO

GRANT SHOPROLERO TO CREATOR;

-- Привилегии роли:
GRANT CREATE SESSION TO SHOPROLERO;
GRANT SELECT ON CREATOR.SH_AKC TO SHOPROLERO;
GRANT SELECT ON CREATOR.SH_PRICE TO SHOPROLERO;
GRANT SELECT ON CREATOR.SH_PROD TO SHOPROLERO;
GRANT SELECT ON CREATOR.SH_SHOP TO SHOPROLERO;
