-- Триггер на INSERT
CREATE OR REPLACE TRIGGER TRG_SH_AKC_INSERT
AFTER INSERT ON SH_AKC
FOR EACH ROW
BEGIN
    INSERT INTO SH_AKC_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER, NEW_NAME)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'INSERT',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.NAME
    );
END;
/

-- Триггер на UPDATE
CREATE OR REPLACE TRIGGER TRG_SH_AKC_UPDATE
AFTER UPDATE ON SH_AKC
FOR EACH ROW
BEGIN
    INSERT INTO SH_AKC_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER, NEW_NAME)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'UPDATE',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.NAME
    );
END;
/

-- Триггер на DELETE
CREATE OR REPLACE TRIGGER TRG_SH_AKC_DELETE
AFTER DELETE ON SH_AKC
FOR EACH ROW
BEGIN
    INSERT INTO SH_AKC_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER)
    VALUES (
        SYSTIMESTAMP,
        :OLD.ID,
        'DELETE',
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );
END;
/
