-- Триггер на INSERT
CREATE OR REPLACE TRIGGER TRG_SH_SHOP_INSERT
AFTER INSERT ON SH_SHOP
FOR EACH ROW
BEGIN
    INSERT INTO SH_SHOP_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER,
                              NEW_URL, NEW_NAME, NEW_NICKNAME, NEW_DEL)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'INSERT',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.URL,
        :NEW.NAME,
        :NEW.NICKNAME,
        :NEW.DEL
    );
END;
/

-- Триггер на UPDATE
CREATE OR REPLACE TRIGGER TRG_SH_SHOP_UPDATE
AFTER UPDATE ON SH_SHOP
FOR EACH ROW
BEGIN
    INSERT INTO SH_SHOP_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER,
                              NEW_URL, NEW_NAME, NEW_NICKNAME, NEW_DEL)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'UPDATE',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.URL,
        :NEW.NAME,
        :NEW.NICKNAME,
        :NEW.DEL
    );
END;
/

-- Триггер на DELETE
CREATE OR REPLACE TRIGGER TRG_SH_SHOP_DELETE
AFTER DELETE ON SH_SHOP
FOR EACH ROW
BEGIN
    INSERT INTO SH_SHOP_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER)
    VALUES (
        SYSTIMESTAMP,
        :OLD.ID,
        'DELETE',
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );
END;
/
