-- Триггер на INSERT
CREATE OR REPLACE TRIGGER TRG_SH_PROD_INSERT
AFTER INSERT ON SH_PROD
FOR EACH ROW
BEGIN
    INSERT INTO SH_PROD_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER,
                              NEW_URL, NEW_NAME, NEW_SHOPID, NEW_DEL)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'INSERT',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.URL,
        :NEW.NAME,
        :NEW.SHOPID,
        :NEW.DEL
    );
END;
/

-- Триггер на UPDATE (только если изменились NAME или SHOPID)
CREATE OR REPLACE TRIGGER TRG_SH_PROD_UPDATE
AFTER UPDATE ON SH_PROD
FOR EACH ROW
WHEN (
    (OLD.NAME != NEW.NAME OR (OLD.NAME IS NULL AND NEW.NAME IS NOT NULL) OR (OLD.NAME IS NOT NULL AND NEW.NAME IS NULL))
    OR
    (OLD.SHOPID != NEW.SHOPID OR (OLD.SHOPID IS NULL AND NEW.SHOPID IS NOT NULL) OR (OLD.SHOPID IS NOT NULL AND NEW.SHOPID IS NULL))
)
BEGIN
    INSERT INTO SH_PROD_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER,
                              NEW_URL, NEW_NAME, NEW_SHOPID, NEW_DEL)
    VALUES (
        SYSTIMESTAMP,
        :NEW.ID,
        'UPDATE',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        :NEW.URL,
        :NEW.NAME,
        :NEW.SHOPID,
        :NEW.DEL
    );
END;
/

-- Триггер на DELETE
CREATE OR REPLACE TRIGGER TRG_SH_PROD_DELETE
AFTER DELETE ON SH_PROD
FOR EACH ROW
BEGIN
    INSERT INTO SH_PROD_HIST (EVENT_DATE, PROD_ID, OPERATION, DB_USER)
    VALUES (
        SYSTIMESTAMP,
        :OLD.ID,
        'DELETE',
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );
END;
/
