
  CREATE TABLE "CREATOR"."SH_PRICE" 
   (	"ID" NUMBER(*,0) DEFAULT "CREATOR"."SH_PRICEID"."NEXTVAL" NOT NULL ENABLE, 
	"AKCID" NUMBER, 
	"PRODID" NUMBER, 
	"PRICE" NUMBER, 
	"OLD_PRICE" NUMBER, 
	"UNIT" VARCHAR2(20), 
	"FROMDATE" DATE DEFAULT ON NULL trunc(sysdate) NOT NULL ENABLE, 
	 CONSTRAINT "UNIQUE_DATE_PROD" UNIQUE ("FROMDATE", "PRODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("AKCID")
	  REFERENCES "CREATOR"."SH_AKC" ("ID") ENABLE, 
	 FOREIGN KEY ("PRODID")
	  REFERENCES "CREATOR"."SH_PROD" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 