-- Привилегии на объекты

GRANT INHERIT PRIVILEGES ON SYS.CREATOR TO CREATOR;
GRANT EXECUTE ON SYS.FILES TO CREATOR;
GRANT READ ON SYS.FILES TO CREATOR;
GRANT WRITE ON SYS.FILES TO CREATOR;
GRANT EXECUTE ON SYS.KEYS TO CREATOR;
GRANT READ ON SYS.KEYS TO CREATOR;
GRANT WRITE ON SYS.KEYS TO CREATOR;
GRANT EXECUTE ON CREATOR.SH TO CREATOR;
GRANT SELECT ON CREATOR.SH_AKC TO CREATOR;
GRANT SELECT ON CREATOR.SH_PRICE TO CREATOR;
GRANT SELECT ON CREATOR.SH_PROD TO CREATOR;
GRANT SELECT ON CREATOR.SH_SHOP TO CREATOR;
GRANT SELECT ON CREATOR.SQ_TEMP_ID TO CREATOR;
GRANT DELETE ON CREATOR.TEMP TO CREATOR;
GRANT INSERT ON CREATOR.TEMP TO CREATOR;
GRANT SELECT ON CREATOR.TEMP TO CREATOR;
GRANT SELECT ON CREATOR.TEMP TO CREATOR;
GRANT UPDATE ON CREATOR.TEMP TO CREATOR;
